version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/sourcecode/blog
hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      runas: root
  Install:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root