version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/sourcecode/blog
    overwrite: yes

file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root