# Generated by Django 4.0.4 on 2022-06-07 04:57

import blog.models
import blog.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=blog.storages.S3ImageStorage, upload_to=blog.models.date_upload_to, verbose_name='이미지'),
        ),
    ]
